export const CONSTANTS = {
    // Timeouts
    TYPING_TIMEOUT_MS: 2000,
    SCROLL_THROTTLE_MS: 500,
    TOAST_DURATION_MS: 3000,
    WEBSOCKET_CONNECT_DELAY_MS: 100,
    SCROLL_TO_BOTTOM_DELAY_MS: 100,
    
    // Pagination
    MESSAGE_LIMIT: 10,
    NEAR_TOP_THRESHOLD_PX: 50,
    
    // WebSocket
    WS_RECONNECT_MAX_ATTEMPTS: 10,
    WS_RECONNECT_BASE_DELAY_MS: 1000,
    WS_RECONNECT_MAX_DELAY_MS: 30000,
    
    // UI
    MAX_MESSAGE_PREVIEW_LENGTH: 50,
    TEXTAREA_MAX_HEIGHT_PX: 120,
    TEXTAREA_MIN_HEIGHT_PX: 44,
    
    // Notifications
    NOTIFICATION_LOAD_DELAY_MS: 0
};

export default CONSTANTS;